server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/config-repo
          clone-on-start: true
  security:    user:      name: haxor
      password: haxor
         